config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root 'sessions#new'

  namespace :api do
    namespace :v1 do
      resources :people do
        resources :analytics
      end
    end
  end

  resources :sessions, only: %i[new create destroy]

  resources :people, only: %i[new create] do
    resources :articles, only: %i[index show]
    resources :analytics, only: %i[index show]
  end
end

app/models/analytic.rb
# frozen_string_literal: true

class Analytic < ApplicationRecord
  belongs_to :person
  validates :keyword, presence: true
  validates :results, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :text, presence: true
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  has_many :analytics
  validates :name, presence: true, uniqueness: true
end

app/controllers/analytics_controller.rb
# frozen_string_literal: true

class AnalyticsController < ApplicationController
  def index
    @person = Person.find_by_id(analytic_params[:person_id])
    @analytics = @person.analytics
                        .select('keyword, count(keyword) as search_count, avg(results) as results, max(created_at) as created_at')
                        .group('keyword')
                        .order('search_count desc, created_at desc')
  end

  private

  def analytic_params
    params.permit(:person_id)
  end
end

app/controllers/api/v1/analytics_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnalyticsController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :find_person
      before_action :find_analytic, only: %i[update destroy]

      # GET /api/v1/people/:person_id/analytics
      def index
        @analytics = @person.analytics.all
        render json: @analytics
      end

      # GET /api/v1/people/:person_id/analytics/1
      def show
        @analytic = @person.analytics.find(analytic_params[:id])
        render json: @analytic
      end

      # POST /api/v1/people/:person_id/analytics
      def create
        @analytic = @person.analytics.new(json_params)

        if @analytic.save
          render json: @analytic, status: :created
        else
          render json: @analytic.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v1/people/:person_id/analytics/1
      def update
        if @analytic.update(json_params)
          render json: @analytic, status: :ok
        else
          render json: @analytic.errors, status: :unprocessable_entity
        end
      end

      # DELETE /api/v1/people/:person_id/analytics/1
      def destroy
        @analytic.destroy
      end

      private

      def find_person
        @person = Person.find_by_id(analytic_params[:person_id])
      end

      def find_analytic
        @analytic = @person.analytics.find_by_id(analytic_params[:id])
      end

      def analytic_params
        params.permit(:person_id, :id)
      end

      # Only allow a list of trusted Body parameters through.
      def json_params
        allowed_data = %(keyword results)
        json_payload.select { |allow| allowed_data.include?(allow) }
      end
    end
  end
end

app/controllers/api/v1/people_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PeopleController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :set_person, only: %i[show update destroy]

      # GET /api/v1/people
      def index
        @people = Person.all
        render json: @people
      end

      # GET /api/v1/people/1
      def show
        render json: @person
      end

      # POST /api/v1/people
      def create
        @person = Person.new(person_params)

        if @person.save
          render json: @person, status: :created
        else
          render json: @person.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v1/people/1
      def update
        if @person.update(person_params)
          render json: @person, status: :ok
        else
          render json: @person.errors, status: :unprocessable_entity
        end
      end

      # DELETE /api/v1/people/1
      def destroy
        @person.destroy
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_person
        @person = Person.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render json: { errors: 'Person not found' }, status: :not_found
      end

      # Only allow a list of trusted parameters through.
      def person_params
        allowed_data = %(name)
        json_payload.select { |allow| allowed_data.include?(allow) }
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def json_payload
    return [] if request.raw_post.empty?

    HashWithIndifferentAccess.new(JSON.parse(request.raw_post))
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  def new
    @person = Person.new
  end

  def create
    @person = Person.create(person_params)
    if @person.valid?
      session[:person_id] = @person.id
      redirect_to person_articles_path(@person.id)
    else
      flash[:error] = 'Error: please try to create an account again.'
      redirect_to new_session_path
    end
  end

  private

  def person_params
    params.require(:person).permit(:name)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    @person = Person.find_by_name(session_params[:name])
    if @person
      session[:person_id] = @person.id
      redirect_to person_articles_path(@person.id)
    else
      flash[:notice] = 'Login is invalid!'
      redirect_to new_session_path
    end
  end

  def destroy
    session[:person_id] = nil
    flash[:notice] = 'You have been signed out!'
    redirect_to new_session_path
  end

  private

  def session_params
    params.permit(:name)
  end
end

app/helpers/analytics_helper.rb
# frozen_string_literal: true

module AnalyticsHelper
end

app/helpers/api/v1/analytics_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module AnalyticsHelper
    end
  end
end

app/helpers/api/v1/people_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module PeopleHelper
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def logged_in?
    !!session[:person_id]
  end

  def current_person
    @current_person ||= Person.find_by_id(session[:person_id]) if !!session[:person_id]
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/views/analytics/_analytic.html.erb
<tr>
  <td><%= analytic.keyword %></td>
  <td><%= analytic.search_count %></td>
  <td><%= analytic.results %></td>
  <td><%= time_ago_in_words(Time.at(analytic.created_at.to_i)) %></td>
</tr>

app/views/analytics/index.html.erb
<div class="card mx-3">
  <div class="card-body">
    <h1><%= current_person.name %> - Analytics</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Keyword</th>
          <th>Search count</th>
          <th>Results (avg)</th>
          <th>Last search</th>
        </tr>
      </thead>
      <tbody>
        <% @analytics.each do |analytic| %>
          <%= render analytic %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/articles/_article.html.erb
<div class="card">
  <div class="card-body"><%= article.text %></div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="header">
    <h1>Articles</h1>
    <div data-controller="search" class="search_box">
      <input data-search-target="keyword" data-action="input->search#input" class="keyword" type="text" placeholder="Search">
      <button data-action="click->search#reset">Reset</button>
    </div>
  </div>
  <p class="found">
    <%= "#{pluralize(@articles.size, "article")} found" %>
  </p>
  <%= render @articles %>
</div>

app/views/articles/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to articles"), person_articles_path(current_person) %>
  <div class="header">
    <h1>
      <%= @article.text %>
    </h1>
  </div>
</main>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item p-3">
          <%= link_to current_person.name, person_articles_path(current_person), class: "nav-link" %>
        </li>
        <li class="nav-item p-3">
          <%= button_to 'Sign out', session_path(current_person), method: :delete, class: "nav-link bg-transparent border-0" %>
        </li>
        <% if request.path[-8..-1] != 'nalytics' %>
          <li class="nav-item p-3">
            <%= link_to 'Analytics', person_analytics_path(current_person), class: "nav-link" %>
          </li>
        <% end %>
        <% if request.path[-8..-1] != 'articles' %>
          <li class="nav-item p-3">
            <%= link_to 'Articles', person_articles_path(current_person), class: "nav-link" %>
          </li>
        <% end %>
      <% else %>
        <% if request.path == '/sessions/new' %>
          <li class="nav-item p-3">
            <%= link_to 'Sign up', new_person_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item p-3">
            <%= link_to 'Sign in', new_session_path, class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/people/new.html.erb
<% if flash[:notice] %>
  <%= content_tag :h1, flash[:notice] %>
<% else %>
  <%= content_tag :h1, "Please Sign up", class: "m-2" %>
<% end %>
<%= form_for @person do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control m-2 w-75", placeholder: "Name" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up", class:'button m-2 w-75' %>
  </div>
<% end %>